### PR TITLE
Header files

### LINKED ISSUE #45: C backend header files problems
The m_value.h header file does not include a header guard which could lead to a double definition compiler error for the m_value struct when including both ir_xxxx.h and m_value.h.

The ir_xxx.h file includes m_value.h inside <> rather than "" which can also cause a compiler error when compiling these files without using the Mlang makefile.

### PR DESCRIPTION
**Pull request by jemsab**
closes #45

### CODE REVIEW

**Comment by rmonat** [comment]
It seems the CI is not triggered correctly. I can investigate tomorrow if needed.

**Comment by jemsab** [comment]
Is this a main branch vs other branch issue ? 

The main branch seems to be pulled by gitlab without any difficulties but here we get a 403.
I think we may indeed need your help as I don't have access to the gitlab clone.

**Comment by rmonat** [comment]
This might be because the branch is not in `MLanguage/mlang` but on your repository. Sorry about that. Could you check by creating a branch on this repo?

**Comment by jemsab** [comment]
No problems, thanks for your help! I've just pushed a gitlab-test-branch branch

**Comment by jemsab** [comment]
lgtm https://gitlab.com/rmonat/mlang/-/pipelines/344702229

**Comment by rmonat** [comment]
Good! Then I suggest prototyping on branches of this repository directly (if that doesn't break a workflow you agreed upon with the rest of the team?).

**Comment by denismerigoux** [comment]
Thanks for this PR James! This indeed solves #45  problem that I had encountered before. I don't have much C development experience and didn't know that was how you solved this annoying double inclusion problem (related to C's horrible module system).

**Pull request merged**
